name: Build and Publish

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          cd pkg
          poetry install --no-cache -vv

      - name: Lint with flake8
        run: |
          cd pkg
          poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Build the package
        run: |
          cd pkg
          poetry build

      - name: Install built package
        run: |
          LATEST_WHL=$(ls pkg/dist/*.whl | sort -V | tail -n 1)
          python -m pip install "$LATEST_WHL" --no-cache-dir
          
      - name: Get pip freeze
        run: |
          pip freeze
      
      - name: Run tests
        run: |
          cd pkg
          poetry run pytest -v tests --junitxml=results.xml
        continue-on-error: True

      - name: Publish to PyPI
        if: github.ref == 'refs/heads/master'
        env:
          POETRY_PYPI_USERNAME: ${{ secrets.POETRY_PYPI_USERNAME }}
          POETRY_PYPI_API_TOKEN: ${{ secrets.POETRY_PYPI_API_TOKEN }}
        run: |
          cd pkg
          poetry publish --build --username "$POETRY_PYPI_USERNAME" --password ""

